### ISSUE TITLE
The downloaded files do not work

### ISSUE THREAD

**Issue by msrk** [tbuser/thingiview.js#8]
when I run the examples on thingiview site, the examples are rendered correctly
when I downloaded the files to my machine, the examples did not run correctly, only a gray background appear
can you please advise

**Comment by jfsaliba** [comment]
Due to the way Javascript handles security, the examples will not properly run when opening files locally on your computer (e.g. with a file:/// address). Instead, they will have to be served as a web page on a server, even if it's just one running on your local machine.

**Comment by eggaweb** [comment]
I had the same problem. I also tested it on my website hosting with the same result, a grey background. After many hours of trying to figure it out, I finally solved the problem. Originally, looking at the source, I thought that only 3 js files were required (thingiview.js, Three.js and plane.js). However, there are more files required:

The whole set can be downloaded here:

https://github.com/tbuser/thingiview.js/downloads

When I copied all the files found in javascripts, it worked!

**Comment by ncrawford** [comment]
I think this project died off.  Take a look at my fork which massively improves the speed at which you can do STL to JSON conversion in binary format.  https://github.com/ncrawford/thingiview.js

**Comment by tbuser** [comment]
This project isn't dead, as a matter of fact I have a big update coming soon. (backporting lots of changes from another project I'm working on)

**Comment by ncrawford** [comment]
My bad. Just assumed from the 1year ago commit .  Did you take out the
array searching in your new version?

**Comment by tbuser** [comment]
Was just checking out what you did.  Looks cool.  However in the new version I'm using a much faster (than my bad php, not sure how it compares to yours) parser I wrote in ruby to convert to three.js's native json format/loader instead of my old hack.

**Comment by ncrawford** [comment]
Ah so it won't be php anymore?

**Comment by tbuser** [comment]
Well the main point of thingiview is to be a javascript wrapper to make viewing things with three.js easier and provide different ways to get STL files into it.  The php was just an example of a way to load STLs.  By the way, I abstracted the ruby code from my other project into a gem at https://github.com/tbuser/mersh and used you're good idea to use an md5 hash lookup for merging vertices.  Thanks!  Now I just need to backport my changes to thingiview to make using three.js json easier. (when I originally wrote thingiview, three.js didn't have the whole loader interface)

I'm going to close this issue because we're talking about things beyond the original issue.  :)
